#!/usr/bin/env python3
"""One-off fix for the doubled NEON unsupervised box CSV.

`TreeBoxes_neon_unsupervised.csv` was generated by concatenating both the
per-site prediction CSVs (with confidence_mean/confidence_std) and the rolled-up
`all_annotations.csv` (the same boxes without confidence columns). Every box
therefore appears twice -- once valued, once NaN-confidence -- which collapses
into ~2.9M duplicate annotations once the packager drops the confidence columns.

This script collapses each box to a single row, preferring the copy that carries
a confidence score, and writes the result back (with a .bak of the original).

The generator (process_neon_unsupervised.py) has been fixed to exclude
all_annotations.csv, so regenerating from scratch is the cleaner long-term fix;
this script repairs the already-produced CSV in place.
"""
import argparse
import shutil

import pandas as pd

DEFAULT_CSV = "/orange/ewhite/DeepForest/neon_unsupervised/TreeBoxes_neon_unsupervised.csv"
BOX_ID = ["image_path", "xmin", "ymin", "xmax", "ymax"]


def dedup(csv_path, write=False):
    df = pd.read_csv(csv_path, low_memory=False)
    n_before = len(df)

    # Prefer the row that has a confidence score (NaN sorts last -> dropped).
    if "confidence_mean" in df.columns:
        df = df.sort_values("confidence_mean", na_position="last")

    deduped = df.drop_duplicates(subset=BOX_ID, keep="first").reset_index(drop=True)
    n_after = len(deduped)

    print(f"{csv_path}")
    print(f"  rows: {n_before} -> {n_after}  (dropped {n_before - n_after})")
    print(f"  unique images: {deduped['image_path'].nunique()}")

    if write:
        backup = csv_path + ".bak"
        shutil.copy(csv_path, backup)
        deduped.to_csv(csv_path, index=False)
        print(f"  backup written: {backup}")
        print(f"  deduped CSV written in place.")
    else:
        print("  (dry run -- pass --write to apply)")
    return deduped


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", default=DEFAULT_CSV, help="Path to the NEON unsupervised box CSV")
    parser.add_argument("--write", action="store_true", help="Write the deduped CSV in place (creates a .bak)")
    args = parser.parse_args()
    dedup(args.csv, write=args.write)
