#!/usr/bin/env python3
"""Regenerate TreePoints_OFO_unsupervised.csv with correct tile-local coordinates.

The original CSV was generated by an older code version whose split_raster call
stored original-raster pixel coordinates in the geometry column instead of
tile-local pixel coordinates, and did not emit x/y columns at all.

This script re-runs the read_file + split_raster coordinate pipeline for each
mission using the processed ortho that is already on disk, writing tiles to a
temp directory so the existing NFS tile images are not touched.
"""

import os
import tempfile
import shutil
import warnings

import geopandas as gpd
import pandas as pd
from deepforest import preprocess
from deepforest.utilities import read_file
from PIL import Image

Image.MAX_IMAGE_PIXELS = None

BASE = '/orange/ewhite/DeepForest/OpenForestObservatory'
IMAGES_DIR = os.path.join(BASE, 'images')
OUT_CSV = os.path.join(IMAGES_DIR, 'TreePoints_OFO_unsupervised.csv')


def _find_files(mission_id: str):
    """Return (ortho_path, treetops_path) or (None, None) if unavailable."""
    mission_dir = os.path.join(BASE, mission_id)
    itd_dir = None
    for name in ('itd_0001', 'itd-0001'):
        d = os.path.join(mission_dir, 'processed_02', name)
        if os.path.isdir(d):
            itd_dir = d
            break
    if itd_dir is None:
        return None, None

    # Prefer the pre-processed uint8 ortho so we don't need to re-convert
    proc_ortho = os.path.join(mission_dir, 'processed_02', 'full', f'{mission_id}_ortho.tif')
    raw_ortho  = os.path.join(mission_dir, 'processed_02', 'full', 'orthomosaic.tif')
    ortho = proc_ortho if os.path.exists(proc_ortho) else (raw_ortho if os.path.exists(raw_ortho) else None)
    if ortho is None:
        return None, None

    for name in (f'{mission_id}_treetops.gpkg', 'treetops.gpkg'):
        t = os.path.join(itd_dir, name)
        if os.path.exists(t):
            return ortho, t
    return None, None


def process_mission(mission_id: str, patch_size: int = 800):
    """Return a DataFrame of tile-local point annotations for one mission."""
    ortho, treetops_path = _find_files(mission_id)
    if ortho is None or treetops_path is None:
        print(f"  {mission_id}: missing ortho or treetops — skipping")
        return None

    gdf = gpd.read_file(treetops_path)
    gdf['image_path'] = os.path.basename(ortho)
    gdf['label'] = 'Tree'

    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        gdf = read_file(gdf, root_dir=os.path.dirname(ortho))

    # Use a temp dir so existing tiles on the NFS mount are not rewritten
    tmpdir = tempfile.mkdtemp()
    try:
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            tiled = preprocess.split_raster(
                gdf,
                path_to_raster=ortho,
                root_dir=os.path.dirname(ortho),
                save_dir=tmpdir,
                patch_size=patch_size,
                patch_overlap=0,
                allow_empty=False,
            )
    finally:
        shutil.rmtree(tmpdir)

    tiled['source'] = 'Young et al. 2025 unsupervised'
    tiled['mission_id'] = mission_id
    tiled['image_path'] = tiled['image_path'].apply(
        lambda fn: os.path.join(IMAGES_DIR, fn)
    )
    return tiled


def main():
    # Discover missions from the existing CSV so we regenerate only what was there
    existing = pd.read_csv(OUT_CSV)
    missions = sorted(
        existing['image_path']
        .apply(lambda p: os.path.basename(p).split('_')[0])
        .unique()
    )
    print(f"Regenerating {len(missions)} missions …")

    records = []
    for i, mid in enumerate(missions, 1):
        print(f"  [{i}/{len(missions)}] {mid}", flush=True)
        df = process_mission(mid)
        if df is not None:
            records.append(df)
            print(f"    → {len(df)} tile annotations", flush=True)

    if not records:
        raise RuntimeError("No missions succeeded.")

    combined = pd.concat(records, ignore_index=True)
    combined.to_csv(OUT_CSV, index=False)
    print(f"\nWrote {len(combined)} annotations across "
          f"{combined['image_path'].nunique()} tiles to:\n  {OUT_CSV}")
    print(f"Columns: {list(combined.columns)}")
    print(f"x range: [{combined['x'].min():.1f}, {combined['x'].max():.1f}]")
    print(f"y range: [{combined['y'].min():.1f}, {combined['y'].max():.1f}]")


if __name__ == '__main__':
    main()
