name: NEON real download test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  neon-test:
    name: "Run real NEON download test"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgeos-dev pandoc

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies (with neon extra)
        run: |
          uv sync --extra unsupervised --dev
          uv pip install nbqa
          uv pip install pytest

      - name: Verify nbqa installation
        run: uv run nbqa --version

      - name: Run real NEON download test only
        env:
          RUN_REAL_NEON: "1"
          # Optionally, provide a NEON token via secrets
          # The test reads neon_token.txt, so we write it here if provided
          NEON_TOKEN: ${{ secrets.NEON_TOKEN }}
        run: |
          if [ -n "$NEON_TOKEN" ]; then echo "$NEON_TOKEN" > neon_token.txt; fi
          uv run python -m pytest -q tests/test_unsupervised_download.py::test_real_download


